### ISSUE TITLE
Example of filter expression

### ISSUE THREAD

**Issue by valerybugakov** [reactore/slick-repository-pattern#1]
Hi, thanks for a great article and repo example! Very helpful stuff.
Could please share an example of `expr` used in  `filterQuery` or a snippet with usage of this method?
```scala
def filterQuery[C <: Rep[_]](expr: T => C)(implicit wt: CanBeQueryCondition[C]) = {
  query.filter(expr).filter(_.isDeleted === false)
}
```

**Comment by yadavan88** [comment]
Hello @valerybugakov , 

The expression is any condition you can apply on the table. 

For eg:, 
```
val query = empRepo.filterQuery(x=> x.firstName==="Yadu" && x.departmentId === 10)
val result:Future[List[Employee]] = db.run(query.result)
```

**Comment by valerybugakov** [comment]
@yadavan88 thanks!
